spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/wave-whisper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - openid
              - profile
              - email
  api:
    paths:
      base: /api
      messages: ${spring.api.paths.base}/messages
